version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rust-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1f8b3qgako8h1"
s3_prefix = "rust-lambda"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
